### PR TITLE
Add R16B01 compatibility

### PR DESCRIPTION
**Pull request by kuenishi**
R16B recommends us using `crypto:hmac/3` which R15B03 does not have. For compatibility I adopted `crypto:hmac_init/2`, `update` and `final`.

### CODE REVIEW

**Comment by shino** [comment]
+1

**Comment by hazen** [comment]
@kuenishi Here is my whole session:

```
git checkout 3d2e63c174a4031a0983cd7910d8fb2321a55144
Note: checking out '3d2e63c174a4031a0983cd7910d8fb2321a55144'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 3d2e63c... Merge pull request #9 from basho/ku-r16
Oculus:/tmp/velvet> make
==> goldrush (get-deps)
==> lager (get-deps)
==> velvet (get-deps)
==> goldrush (compile)
Compiled src/glc.erl
Compiled src/glc_lib.erl
Compiled src/glc_code.erl
Compiled src/gr_context.erl
Compiled src/glc_ops.erl
Compiled src/gre.erl
==> lager (compile)
Compiled src/lager_util.erl
Compiled src/lager_transform.erl
Compiled src/lager_app.erl
Compiled src/lager_backend_throttle.erl
Compiled src/lager_config.erl
Compiled src/lager.erl
Compiled src/lager_console_backend.erl
Compiled src/error_logger_lager_h.erl
Compiled src/lager_default_formatter.erl
Compiled src/lager_crash_log.erl
Compiled src/lager_handler_watcher.erl
Compiled src/lager_handler_watcher_sup.erl
Compiled src/lager_msg.erl
Compiled src/lager_file_backend.erl
Compiled src/lager_sup.erl
Compiled src/lager_format.erl
Compiled src/lager_stdlib.erl
Compiled src/lager_trunc_io.erl
==> velvet (compile)
compile: warnings being treated as errors
src/stanchion_utils.erl:51: crypto:sha_mac/2 is deprecated and will be removed in in a future release; use crypto:hmac/3
src/stanchion_utils.erl:52: crypto:md5/1 is deprecated and will be removed in in a future release; use crypto:hash/2
make: *** [compile] Error 1
```

**Comment by kellymclaughlin** [comment]
@javajolt i see the same issue. I can open a pr to fix that.

**Comment by kuenishi** [comment]
Commented on this issue: https://github.com/basho/basho_bench/pull/87#issuecomment-24753850

I thought we didn't need Makefile in velvet, because velvet was just a library.

**Comment by kellymclaughlin** [comment]
Opened #11 to add the conditionals to the Makefile. Shouldn't do any harm to have them there.

**Pull request merged**
