### PR TITLE
Add update_user function

### PR DESCRIPTION
**Pull request by kellymclaughlin**
This is to be used for serialized user updates and is a complement to [this](https://github.com/basho/stanchion/issues/53) Stanchion issue.

### CODE REVIEW

**Comment by reiddraper** [comment]
I'm getting build errors using this from within Riak CS. Maybe try and merge the lager 2.0 changes into here? Or is there another way?

```
ERROR: Dependency dir /Users/reid/Documents/repos/basho/riak_cs/deps/lager failed application validation with reason:
{version_mismatch,{"/Users/reid/Documents/repos/basho/riak_cs/deps/lager/src/lager.app.src",
                   {expected,"1.2.2"},
                   {has,"2.0.0"}}}.
ERROR: 'get-deps' failed while processing /Users/reid/Documents/repos/basho/riak_cs/deps/velvet: rebar_abort
make: *** [deps] Error 1
```

**Comment by kellymclaughlin** [comment]
Good point. I forgot that was an issue. Let me just update that lager dep as a commit here to make things simple.

**Comment by reiddraper** [comment]
woot that built

**Comment by reiddraper** [comment]
+1

**Pull request closed without merging**
