### PR TITLE
Add conditionals to Makefile for R16 support

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Add conditionals to Makefile so that the project can be built standalone. This
accounts for a change in the Erlang crypto API between R15 and R16.

### CODE REVIEW

**Comment by jaredmorrow** [comment]
Andrew did the following so that the Makefiles didn't need to be changed:

https://github.com/basho/riak_kv/commit/76d235c534a588b43aed449dcac3c3ea09d17c6e

Here is the toplevel Riak PR https://github.com/basho/riak/pull/350

**Comment by kellymclaughlin** [comment]
> Andrew did the following so that the Makefiles didn't need to be changed:

Oh I like that. We should maybe just do that instead for all of Riak CS.

**Comment by kellymclaughlin** [comment]
The change to `rebar.config.script` could look like this: https://gist.github.com/kellymclaughlin/b27755fc6eda6b55c373

**Comment by kuenishi** [comment]
I also like Andrew's idea. I opened a new PR based on @kellymclaughlin 's gist , so I hope you take a look on it.

**Pull request closed without merging**
